[package]
name = "akebi"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.22"
soft-aes = "0.2"
hex-literal = "0.4"
hmac = "0.12.1"
sha2 = "0.10"
toml = "0.8"
